### ISSUE TITLE
Vision Pro APP Setting

### ISSUE THREAD

**Issue by kavinwkp** [YanjieZe/Humanoid-Teleoperation#3]
感谢作者开源，请问只有设置Vision Pro APP的时候要用到苹果电脑，还是整个项目都只能用苹果电脑
另外支持其他类型头显吗，比如quest3

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. Macbook is only needed when installing APP on Apple Vision Pro.
We do not use quest3 in this project, but I think a lot of components could be shared.
