### ISSUE TITLE
Missing directory teleop_real

### ISSUE THREAD

**Issue by chaitanya1chawla** [YanjieZe/Humanoid-Teleoperation#4]
Hi,

The ReadMe.md (https://github.com/YanjieZe/Humanoid-Teleoperation/blob/main/humanoid_teleoperation/README.md) says we need to install the directory teleop-real, however, I can't find it in the repository.

Has the code been made publicly available for this directory?

**Comment by YanjieZe** [comment]
Hi, thank you for the interest. I think this line should be actually removed from README. The full code has been released in this repo, so no additional repo is needed. 
I have updated README. Thank you!
