### ISSUE TITLE
 What are the differences between the compiled AVP program and the original AVP streamer program?

### ISSUE THREAD

**Issue by adonisyang999** [YanjieZe/Humanoid-Teleoperation#7]
Hi,

Thank you for your excellent work! I have a question regarding the AVP data format.

When I  use the compiled AVP program mentioned [here](https://github.com/YanjieZe/Humanoid-Teleoperation/tree/main/vision_pro_app), I used the following code to extract data:

```
from avp_stream import VisionProStreamer
avp_ip = "192.168.137.122"   # example IP
s = VisionProStreamer(ip=avp_ip, record=True)

while True:
    r = s.latest
    print(r.keys())

```

The resulting keys are:
`dict_keys(['left_wrist', 'right_wrist', 'left_fingers', 'right_fingers', 'head', 'left_pinch_distance', 'right_pinch_distance', 'right_wrist_roll', 'left_wrist_roll'])`

However, I noticed that the data does not include information about the arm or elbow posture. Is this the expected output? Is there a way to retrieve arm or elbow posture data?

Thank you for your help!

**Comment by YanjieZe** [comment]
Hi, i think the main difference is we visualize the robot view in the APP.
